# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @useDynLib FibonacciPackage
#' @importFrom Rcpp sourceCpp
fibonacci_c <- function(x) {
    .Call('_FibonacciPackage_fibonacci_c', PACKAGE = 'FibonacciPackage', x)
}

